Neos:
  Flow:
    mvc:
      routes:
        'Flowpack.Listable':
          position: 'before Neos.Neos'
  Neos:
    fusion:
      autoInclude:
        Flowpack.Listable: true
    userInterface:
      translation:
        autoInclude:
          Flowpack.Listable:
            - 'NodeTypes/*'
